# -*- coding: utf-8 -*-
"""combinacao_dataframe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1duc-CUpgufNmK06r67K-iloXkTFT9pgt
"""

# como concatenar data_frames
# primeiramente criamos uma lista com os data frames, apos isso, usamos a comando pandas.concat(lista)

import pandas
data_frame_1 = pandas.DataFrame({
    'A': ['A1', 'A2', 'A3'],
    'B': ['B1', 'B2', 'B3'],
    'C': ['C1', 'C2', 'C3'],
},index = [0,1,2])

data_frame_2 = pandas.DataFrame({
    'A': ['A4', 'A5', 'A6'],
    'B': ['B4', 'B5', 'B6'],
    'C': ['C4', 'C5', 'C6'],
    'D': ['D1', 'D2', 'D3'],
},index = [3,4,5])

data_frame_3 = pandas.DataFrame({
    'A': ['A7', 'A8', 'A9'],
    'B': ['B7', 'B8', 'B9'],
    'C': ['C7', 'C8', 'C9'],
},index = [6,7,8])
lista = [data_frame_1, data_frame_2, data_frame_3]

new_df = pandas.concat(lista)
print(f"{new_df}\n")


# Podemos colocar chaves para cada dataframe também
new_df_keys = pandas.concat([data_frame_1, data_frame_2, data_frame_3], keys = ['df1', 'df2', 'df3'])
print(f'{new_df_keys}\n')

# como olhar alguma key de uma concatenação de data frames
new_df_keys.loc['df3']


# outra maneira de concatenar
conc_2 = data_frame_1.append(data_frame_2)
print(f'{conc_2}\n')