# -*- coding: utf-8 -*-
"""visualizacao_data_frame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dqUg3zIsTTC13oZ8VR4ud11F3PrXE2aX
"""

# Como visualizar dados

import numpy
import pandas
matriz = numpy.random.randn(5, 4)
data_frame = pandas.DataFrame(matriz, index = [1,2,3,4,5], columns = ['A', 'B', 'C', 'D'])

# como pegar determinadas linhas começando da primeira ou da ultima
print(data_frame.head(2))
print("")
print(data_frame.tail(2))
print("")

# como ver apenas os index ou colunas
linhas = data_frame.index
colunas = data_frame.columns
print(f"colunas: {colunas}\nlinhas: {linhas}\n")

# caso a gnt queira so a matriz
matizz = data_frame.to_numpy()

# Como obter a transposta do data frame
trans = data_frame.T